apiVersion: v1
kind: Service
metadata:
  name: {{ include "cosmotech-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmotech-gateway.labels" . | nindent 4 }}
  annotations:
    email: "platform@cosmotech.com"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.managementPort }}
      targetPort: http-management
      protocol: TCP
      name: http-management
  selector:
    {{- include "cosmotech-gateway.selectorLabels" . | nindent 4 }}
